name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🏗 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 🏗 Restore dependencies
        run: dotnet restore src

      - name: 🏗 Build
        run: dotnet build src --no-restore

      - name: 🦾 Install browser for Playwright tests
        shell: pwsh
        run: src/CSharpPlaywrightDemoTests/bin/Debug/net8.0/playwright.ps1 install --with-deps chromium

      - name: Test
        run: dotnet test src --no-build --verbosity normal

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.0.0
        with:
          name: allure-results
          path: src/CSharpPlaywrightDemoTests/bin/Debug/net8.0/allure-results
          if-no-files-found: error
          retention-days: 20

      - name: Clean up gh-pages branch (optional)
        run: |
          git checkout -f gh-pages
          git rm -rf .

  report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: allure-results
          path: ./allure-results

      - name: Get Allure history (optional)
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        # uses: peaceiris/actions-github-pages@v3.1.12
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
