name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🏗 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 🏗 Restore dependencies
        run: dotnet restore src

      - name: 🏗 Build
        run: dotnet build src --no-restore

      - name: 🦾 Install browser for Playwright tests
        shell: pwsh
        run: src/CSharpPlaywrightDemoTests/bin/Debug/net8.0/playwright.ps1 install --with-deps chromium

      - name: Test
        run: dotnet test src --no-build --verbosity normal
